image:
  file: .gitpod.Dockerfile

tasks:
  - command: cd app && trunk watch # WASM build
    command: cargo run # Rocket server
    prebuild: cd app && trunk build # Prebuild app so running trunk-serve would be much faster

ports:
  - port: 8000
    onOpen: open-preview

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    